"""fix_reviews

Revision ID: d5aa5bc92197
Revises: 61c16add9178
Create Date: 2021-01-21 16:02:04.431066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5aa5bc92197'
down_revision = '61c16add9178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_films')
    op.drop_index('login', table_name='exam_users')
    op.drop_table('exam_users')
    op.drop_table('exam_roles')
    op.drop_table('exam_posters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_posters',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('file_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('mime_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('md5_hash', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('exam_roles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('exam_users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('login', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('middle_name', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['exam_roles.id'], name='exam_users_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('login', 'exam_users', ['login'], unique=True)
    op.create_table('exam_films',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('discription', mysql.TEXT(), nullable=False),
    sa.Column('production_year', mysql.YEAR(display_width=4), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('director', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('screenwriter', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('actors', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('poster_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['poster_id'], ['exam_posters.id'], name='exam_films_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
